/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TimeOfDay = IDL.Record({ 'hour' : IDL.Nat, 'minute' : IDL.Nat });
export const AttendanceRecord = IDL.Record({
  'lateMinutesIn' : IDL.Nat,
  'isPresent' : IDL.Bool,
  'actualInTime' : IDL.Opt(TimeOfDay),
  'date' : IDL.Text,
  'lateForIn' : IDL.Bool,
  'lateForOut' : IDL.Bool,
  'actualOutTime' : IDL.Opt(TimeOfDay),
  'lateMinutesOut' : IDL.Nat,
});
export const Staff = IDL.Record({
  'id' : IDL.Nat,
  'scheduledInTime' : TimeOfDay,
  'name' : IDL.Text,
  'scheduledOutTime' : TimeOfDay,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStaff' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMonthlyAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(AttendanceRecord)))],
      ['query'],
    ),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTime' : IDL.Func([], [TimeOfDay], ['query']),
  'getMonthlyAttendanceForStaff' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool],
      [AttendanceRecord],
      [],
    ),
  'removeStaff' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInTime' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [AttendanceRecord],
      [],
    ),
  'submitOutTime' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [AttendanceRecord],
      [],
    ),
  'updateStaffTimes' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TimeOfDay = IDL.Record({ 'hour' : IDL.Nat, 'minute' : IDL.Nat });
  const AttendanceRecord = IDL.Record({
    'lateMinutesIn' : IDL.Nat,
    'isPresent' : IDL.Bool,
    'actualInTime' : IDL.Opt(TimeOfDay),
    'date' : IDL.Text,
    'lateForIn' : IDL.Bool,
    'lateForOut' : IDL.Bool,
    'actualOutTime' : IDL.Opt(TimeOfDay),
    'lateMinutesOut' : IDL.Nat,
  });
  const Staff = IDL.Record({
    'id' : IDL.Nat,
    'scheduledInTime' : TimeOfDay,
    'name' : IDL.Text,
    'scheduledOutTime' : TimeOfDay,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStaff' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMonthlyAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(AttendanceRecord)))],
        ['query'],
      ),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTime' : IDL.Func([], [TimeOfDay], ['query']),
    'getMonthlyAttendanceForStaff' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool],
        [AttendanceRecord],
        [],
      ),
    'removeStaff' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInTime' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [AttendanceRecord],
        [],
      ),
    'submitOutTime' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [AttendanceRecord],
        [],
      ),
    'updateStaffTimes' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };